[package]
name = "mmoxi"
version = "0.1.1"
authors = ["Christian Krause <christian.krause@idiv.org>"]
description = "spectrum scale tools"
license = "GPL-3.0-or-later"
readme = "README.md"
documentation = "https://github.com/idiv-biodiversity/mmoxi"
homepage = "https://github.com/idiv-biodiversity/mmoxi"
repository = "https://github.com/idiv-biodiversity/mmoxi"
keywords = ["gpfs", "prometheus", "spectrum-scale"]
categories = ["command-line-utilities", "filesystem"]
edition = "2021"

[dependencies]
anyhow = "1"

[dependencies.clap]
version = "3"
features = ["cargo", "wrap_help"]

[profile.release]
lto = true
