---

name: rust-audit

on:
  pull_request:
    paths:
      - '.github/workflows/rust-audit.yml'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  push:
    branches:
      - main
      - wip/next
    paths:
      - '.github/workflows/rust-audit.yml'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  schedule:
    - cron: '0 6 * * 1'

jobs:
  cargo-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: rustsec/audit-check@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

...
