---

name: rust

on:
  pull_request:
    paths:
      - '.github/workflows/rust.yml'
      - 'rust-toolchain.toml'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '**.rs'
  push:
    branches:
      - main
      - wip/next
    paths:
      - '.github/workflows/rust.yml'
      - 'rust-toolchain.toml'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '**.rs'

env:
  CARGO_TERM_COLOR: always
  CARGO_TERM_VERBOSE: true

jobs:

  test:
    name: test
    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v5

      - name: set up rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
          rustflags: ''

      - name: check formatting
        run: cargo fmt --check

      - name: cargo check
        run: cargo check

      - name: cargo clippy
        run: cargo clippy

      - name: cargo build
        run: cargo build

      - name: cargo test
        run: cargo test

...
